### ISSUE TITLE
无法绑定频道

### ISSUE THREAD

**Issue by tiankongsang** [tinyRatP/Docker-Hub#6]
# 无法绑定频道   

## 环境

全新搭建的 `ehForwarderBot`  

## 状况

绑定**频道**的时候，无法绑定出错

### bot报错

```python
EFB Telegram 主端遇到错误 'Chat' object has no attribute 'uid'。
来自状态：{'update_id': 22305140, 'message': {'message_id': 21348, 'date': 1580838869, 'chat': {'id': ********, 'type': 'private', 'username': '********', 'first_name': '********'}, 'forward_from_chat': {'id': ********, 'type': 'channel', 'title': '微信公众号', 'username': '********'}, 'forward_date': 1580838866, 'text': '/start NTQ5NzkwMjM4LjIxMzQ3', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'forward_from_message_id': 26, 'from': {'id': ********, 'first_name': '********', 'is_bot': False, 'username': '********', 'language_code': 'zh-hans'}}, '_effective_user': {'id': ********, 'first_name': '********', 'is_bot': False, 'username': '********', 'language_code': 'zh-hans'}, '_effective_chat': {'id': ********, 'type': 'private', 'username': '********', 'first_name': '********'}, '_effective_message': {'message_id': 21348, 'date': ********, 'chat': {'id': ********, 'type': 'private', 'username': '********', 'first_name': '********'}, 'forward_from_chat': {'id': ********, 'type': 'channel', 'title': '微信公众号', 'username': '********'}, 'forward_date': ********, 'text': '/start NTQ5NzkwMjM4LjIxMzQ3', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'forward_from_message_id': 26, 'from': {'id': ********, 'first_name': '********', 'is_bot': False, 'username': '********', 'language_code': 'zh-hans'}}}。请检查错误日志。
```

### 错误日志

```python
2020-02-04 17:54:30,804 [ERROR]: efb_telegram_master (__init__.error; __init__.py:529)
    Unhandled telegram bot error!
Update {'update_id': 22305140, 'message': {'message_id': 21348, 'date': 1580838869, 'chat': {'id': ********, 'type': 'private', 'username': '********', 'first_name': '********'}, 'forward_from_chat': {'id': ********,'type': 'channel', 'title': '微信公众号', 'username': '********'}, 'forward_date': 1580838866, 'text': '/start NTQ5NzkwMjM4LjIxMzQ3', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'forward_from_message_id': 26, 'from':{'id': ********, 'first_name': '********', 'is_bot': False, 'username': '********', 'language_code': 'zh-hans'}}, '_effective_user': {'id': ********, 'first_name': '********', 'is_bot': False, 'username': '********', 'language_code': 'zh-hans'}, '_effective_chat': {'id': ********, 'type': 'private', 'username': '********', 'first_name': '********'}, '_effective_message': {'message_id': 21348, 'date': 1580838869, 'chat': {'id': ********, 'type': 'private', 'username': '********', 'first_name': '********'}, 'forward_from_chat': {'id': ********, 'type': 'channel', 'title': '微信公众号', 'username': '********'}, 'forward_date': 1580838866, 'text': '/start NTQ5NzkwMjM4LjIxMzQ3', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'forward_from_message_id': 26, 'from': {'id': ********, 'first_name': '********', 'is_bot': False, 'username': '********', 'language_code': 'zh-hans'}}} caused error 'Chat' object has no attribute 'uid'. Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/__init__.py", line 459, in error
    raise error
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/__init__.py", line 318, in start
    self.chat_binding.link_chat(update, context.args)
  File "/usr/local/lib/python3.7/site-packages/efb_telegram_master/chat_binding.py", line 493, in link_chat
    tg_chat_to_link = forwarded_chat.uid
AttributeError: 'Chat' object has no attribute 'uid'
```

**Comment by tinyRatP** [comment]
我这边没有重现此问题，可以删除相关容器，重现创建试试。

**Comment by tiankongsang** [comment]
# 重试了一下

> 这次什么都没动

##  环境

删除了本地的文件 

删除镜像（images）`ehforwarderbot_bot` `richardchien/cqhttp` `python`

## 下载仓库

```shell
git clone https://github.com/tinyRatP/Docker-Hub.git
```

## 搭建 ehforwarderbot

- 按照文档修改 `Token` 和 `admins`  
- 执行命令
- 扫码登陆

##  打开 TG bot

![TG bot](https://user-images.githubusercontent.com/20697404/73844521-ae32a580-485b-11ea-912f-0022266c6744.png)

日志跟上面反馈一样

**Comment by tiankongsang** [comment]
没有找到同样的案例就很麻烦，正在曲线救国中....

**Comment by tiankongsang** [comment]
哦？ 更新了 requirements.txt

**Comment by tiankongsang** [comment]
# 更新 requirements.txt 后，问题解决

关闭 `issues`
